services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: apihabitos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: